### ISSUE TITLE
"Test drive" mode for submission

### ISSUE THREAD

**Issue by jgaff** [nih-cfde/submission-workflow#1]
Submission flag `test_sub` to cause a normal ingest into DERIVA, that gets immediately deleted after a successful ingest, and (a clearly-marked-as-test) success message sent to the user - no curation or other processing.

**Comment by jgaff** [comment]
@lliming @rpwagner My current implementation here uses the Flow to delete the catalog after ingestion. Is it instead desired that the AP itself takes the `test_sub` flag and deletes the catalog, or is it sufficient that the Flow handles the flag?

**Comment by lliming** [comment]
I don't have an opinion one way or another, as long as it works. @rpwagner ?

**Comment by rpwagner** [comment]
@jgaff I don't have an opinion either way. If you have it working, that's good enough for me.

**Comment by jgaff** [comment]
Update on the current state of this task: The Flow no longer handles the delete request, as the Flow has been trimmed down significantly (mostly with the removal of curation). The `cfde-submit` client can pass in the `test_sub` flag to the Flow, which is handed to the AP, but the AP doesn't handle or respect the flag at this time.
I'm wondering if it's desirable for the delete-a-test-catalog functionality to live in `cfde-deriva` instead of the AP, or if the AP should still be interfacing directly with catalogs for this case.

**Comment by NickolausDS** [comment]
This issue is mostly finished, but for the current Epic2 code the action provider doesn't respond to the `test_sub` flag and delete the new submission. Currently, this hasn't been a problem and we've simply allowed test submissions to lurk in the registry. 

I'll stick this issue in the backlog, so it can be finished if we want to finish adding test submissions as a feature.

**Comment by ACharbonneau** [comment]
I think the functionality I needed here has been fixed with adding a testing account https://github.com/nih-cfde/security/issues/15 so I think this is done
