### ISSUE TITLE
AP should validate user in DCC Group

### ISSUE THREAD

**Issue by jgaff** [nih-cfde/submission-workflow#10]
Action Provider should validate that user submitting with a DCC is in appropriate DCC Globus Group. How the AP determines which group to check is out-of-scope; this issue tracks only the checking of an assumed-to-be-correctly-defined group.

**Comment by lliming** [comment]
Where is the "How the AP determines which group to check" part being determined/resolved?

**Comment by jgaff** [comment]
There has been discussion of either using a dynamic config file for the AP, akin to the submission client's, having the AP read the DERIVA registry catalog with the DCC metadata directly, or some other solution. I am not aware of where this conversation may be ongoing, and the ultimate decision depends on how the registry catalog is defined and interacted with.

**Comment by jgaff** [comment]
It seems that this task is going to be handled by `cfde-deriva` in the future, after the user-informaiton-passing is worked out.

**Comment by karlcz** [comment]
I think we should close this as redundant?  I think there are two enforcement points already in existence:
- ACLs on the automate side
- Check against registry within the `cfde_deriva.submission.Submission.ingest()` routine

**Comment by NickolausDS** [comment]
Yes, agreed. I'll go ahead and close this now.
