### ISSUE TITLE
Document AP/GCS VM inventory in VPCs

### ISSUE THREAD

**Issue by jgaff** [nih-cfde/submission-workflow#16]
Documentation for VM inventory in STRIDES VPCs

**Comment by RLC-DCPPC** [comment]
@jgaff to work on this week and present next Monday.  Want this done early so it can be part of the transition to @NickolausDS

**Comment by jgaff** [comment]
The inventory and installation instructions are finished. @rpwagner where should the Google Doc link be, so the document is accessible to CFDE but (I assume) not public?

**Comment by jgaff** [comment]
The documentation has been added to the systems-infrastructure repo.
