### ISSUE TITLE
Upgrade Action Provider to support epic2 ingests

### ISSUE THREAD

**Issue by NickolausDS** [nih-cfde/submission-workflow#18]
The current Action Provider submission process uses the older [epic1](https://github.com/nih-cfde/cfde-deriva/commit/f9e3c9b6a446c73f0090aff7770a376a0d4e4f7c) code for doing ingests into Deriva. 

The Action provider needs to be upgraded to use [epic2](https://github.com/nih-cfde/cfde-deriva/tree/epic2_202101) instead. 

This shouldn't require many or any changes to the current Flow Definition, but it will require substantial changes for how the ingest process itself works. Epic1 type ingests now no longer function on the `ap-dev.nih-cfde.org` server.

Checklist:

- [x] Verify independent standalone submission to epic2 is possible with the [cfde-deriva tooling here](https://github.com/nih-cfde/cfde-deriva/blob/epic2_202101/cfde_deriva/submission.py).
- [x] Overhaul the action provider to use epic2

**Comment by NickolausDS** [comment]
Update on the work for this issue, I have been able to submit datasets with the newest cfde-deriva code on the epic2 branch. Migrating the Action Provider to using the epic2 code is getting close, but there are still some problems with getting successful ingests through the action provider. 

See progress here: https://github.com/nih-cfde/deriva-action-provider/pull/8

**Comment by NickolausDS** [comment]
This is finished, with the caveat of #23

**Comment by NickolausDS** [comment]
Reopening until #23 is fixed

**Comment by NickolausDS** [comment]
@lliming We've been doing epic2 ingests a while now, I think we can consider this done?

**Comment by lliming** [comment]
Agreed.
