### ISSUE TITLE
Upgrade globus-action-provider-tools to use version 0.10.5

### ISSUE THREAD

**Issue by NickolausDS** [nih-cfde/submission-workflow#19]
Current version is 0.6, and many changes have been added since then.

The Deriva Action Provider would be well suited to the [flask decorator model here](https://action-provider-tools.readthedocs.io/en/latest/examples/apt_blueprint.html).

There's one small 'gotcha' for upgrading these tools. The current scopes were registered a couple years ago and have some legacy properties associated with them. This results in invalid `401` responses when request with valid tokens are submitted to the service. To fix this, a slight change is needed to the `ActionProviderBlueprint` class `globus_auth_client_name` value, which must be added to avoid these invalid 401 responses:

```
aptb = ActionProviderBlueprint(
    name="apt",
    import_name=__name__,
    url_prefix="/apt",
    provider_description=description,
    globus_auth_client_name='cfde_ap_demo',
)
```

**Comment by ACharbonneau** [comment]
Does anyone know if this is done?

**Comment by lliming** [comment]
Yes, it's done.
