### ISSUE TITLE
Setup automated tests

### ISSUE THREAD

**Issue by NickolausDS** [nih-cfde/submission-workflow#20]
Unit tests are not automatically run. Setup automated tests to run every time code is pushed to dev/master. 

This should be quite trivial if the nih-cfde org is setup to use Jenkins or Travis.

**Comment by DavidMichaelKelly** [comment]
We are now using github actions. The testing is run when there is a push or pull request. It tests everything using python versions 3.6, 3.7, 3.8, and 3.9 on the latest version of ubuntu. Within the container it installs all the prerequisites and then runs the linter and unit tests. It gives you a little mark next to the commit (a green check if everything passed, a red x if it failed). You can also go back and view the outputs of each individual step (image attached). At the moment this is in the bug fix branch, but will be merged back into main for the next release.

![Screenshot from 2021-03-11 12-43-48](https://user-images.githubusercontent.com/1781986/110839403-1e82d600-8269-11eb-9ef8-49d216fd308d.png)
