### ISSUE TITLE
Setup message broker to consume ingest tasks

### ISSUE THREAD

**Issue by NickolausDS** [nih-cfde/submission-workflow#26]
The problem here #23 seemed to reveal that submissions in multiple processes caused the WSGI server to hang the newly spawned process. Threading instead isn't really an option, due to the Deriva ingest not being thread safe. The final possible option is a message broker to consume tasks and run in different processes. That way, the Action Provider can truly run multiple ingest tasks simultaneously without each task harming another.

**Comment by ACharbonneau** [comment]
is this still needed?

**Comment by DavidMichaelKelly** [comment]
This has been resolved by using the combination of funcx and parallelcluster
