### ISSUE TITLE
Add basic datapackage validation to client pre-submission

### ISSUE THREAD

**Issue by jgaff** [nih-cfde/submission-workflow#3]
Validate datapackage as legitimate package in submission client before submission. This does not include validating C2M2 metadata or foreign key relations.

**Comment by karlcz** [comment]
I think we should factor this code so that it can be reused in the client tool and in the action provider to enforce validity in both places.

**Comment by jgaff** [comment]
The client-based validation is a convenience to stop users from submitting very invalid data. The AP enforces this validation and more simply by virtue of submitting to DERIVA (the catalog will reject invalid data). I'm not sure why validating the data in the AP before ingesting into DERIVA is needed - if badly invalid data are being accepted into DERIVA, isn't that a bigger problem?

**Comment by jgaff** [comment]
The (at this point, temporary) validation is in the client. Client-side validation is expected to change, but the validation this issue refers to is complete.
