### ISSUE TITLE
Switch to newer frictionless python package?

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/submission-workflow#31]
There is a newer product from the upstream frictionless project
https://github.com/frictionlessdata/frictionless-py

This has somewhat less crazy third-party dependency chain and seems like it is the package they will be continuing to maintain.

The code in cfde-deriva at https://github.com/frictionlessdata/frictionless-py  might be usable directly or at least serve as an example of its use.  I kept it as a `classmethod` with the idea that it could be used in more than one context.  It just operates on the unpacked datapackage files on disk and has an optional callback param if you want to supply some custom code to inspect the report datastructure before this routine has a chance to look and raise errors.

**Comment by NickolausDS** [comment]
Was this for the action provider? I noticed cfde-deriva required this dependency, although IIRC it wasn't explicit in the requirements and had to be installed manually.

**Comment by karlcz** [comment]
I added the dependency.  But no, I mean the validation in the submission tool should change to this newer frictionless software as well

**Comment by DavidMichaelKelly** [comment]
I believe this is an older issue that may be resolved. It doesn't look like frictionless is used by the cfde-submit validation routines, and it's not currently listed in the requirements of cfde-submit or deriva-action-provider.
