### ISSUE TITLE
Ensure users in the DCC Submitters group are granted access to the cfde-submit tool

### ISSUE THREAD

**Issue by NickolausDS** [nih-cfde/submission-workflow#33]
In order for folks to run the cfde-submit tool, they need to have read and run access to the Globus Automate flow. Read/run access are set on an automate flow at deployment time, so the full submitters list should be accessible by the flow deployment tooling on the https://github.com/nih-cfde/deriva-action-provider. Submitters also need access to the GCS endpoints for staging data on each GCS endpoint.

Flow Submitters Access Requirements on dev/staging/prod:

- Read Access for Flow Submission
- Run Access for Flow Submission
- Write Access on the GCS endpoint for staging datasets

The list of Submitters has been created here: https://github.com/nih-cfde/security/issues/8

There are currently 11 Submitters in the groups above. That means approximately (3 environments, 3 ACLs, 11 Submitters) 99 ACL that need to be set correctly. We should probably incorporate this into the flow deployment scripts to ensure everything is set correctly if we need to add/remove Submitter groups.

**Comment by NickolausDS** [comment]
@DavidKelly999 I realize some of the stuff I was working on relates directly to this work. We need to make sure the dir-structure and ACLs for each DCC match up on the GCS endpoint for #35. Originally, I was going to have the action provider create the directories and assign ACLs if directories don't exist, but we also need to do the same work when deploying the action provider flow, to make sure the `runnable_by` attribute on the flows line up with the DCC submitters. 

Instead of having some code responsible for ensuring the correct permissions as deployment scripts, and some of the same code embedded in the Action Provider, I think it makes more sense to contain all of the code in the deployment scripts. 

I added a small function to automatically create directories if they don't exist here: https://github.com/nih-cfde/deriva-action-provider/pull/14/files#diff-168b0e27dec9c5146430506ec5c826075c0e2190fd0ff8f204f3293f10f68df5R38.

**Comment by DavidMichaelKelly** [comment]
This issue seems to be resolved with deriva-action-provider pull request 13. The /CFDE/public/<dcc> directory gets created, acls are set to allow the group read/write access, and the data is uploaded to the new directory.
