### ISSUE TITLE
Ensure submission ids are UUID formatted strings

### ISSUE THREAD

**Issue by NickolausDS** [nih-cfde/submission-workflow#37]
Currently, the submission ids appear to be hex strings, they should be switch to be uuid formatted strings.

**Comment by NickolausDS** [comment]
Action IDs are generated by the Action Provider itself. This is custom in the current action provider, but can be overrided in the newer action provider tools here: 

https://github.com/globus/action-provider-tools/blob/master/globus_action_provider_tools/data_types.py#L135

Related to #19

**Comment by karlcz** [comment]
Should the same UUID-format string start appearing in the archive file names too?

**Comment by NickolausDS** [comment]
Yes, that's captured in another ticket. A few issues we discussed on slack are very similar:

* Ensure submission IDs are UUIDS (this ticket): #37
* Rename submission ids by timestamp/uuid: #36 
* Ensure ingested datasets are read-only: #35
