### ISSUE TITLE
Publish submission client to PyPI

### ISSUE THREAD

**Issue by jgaff** [nih-cfde/submission-workflow#4]
@lliming @rpwagner What PyPI accounts should be given ownership of the submission client package on PyPI? I obviously need to not be the only one with publication rights.

**Comment by rpwagner** [comment]
@NickolausDS and @mikedarcy for now.

**Comment by NickolausDS** [comment]
On PYPI: [Me](https://pypi.org/user/nicksaint/) and [Mike](https://pypi.org/user/mikedarcy/)

**Comment by NickolausDS** [comment]
I was looking at publishing to PyPi, and noticed some oddities. The package name is actually called the cfde_client, even though the repo is called the deriva-flow-client. Just to double check, we want this to be the deriva-flow-client, right? That would also mean changing the command from `cfde` to `dfc`. 

Usage will look like the following:

```
$ pip install deriva-flow-client
$ dfc login
$ dfc run my_data_package.zip
$ dfc status
$ dfc logout
```

@rpwagner @mikedarcy @jgaff opinions?

**Comment by jgaff** [comment]
I think users aren't going to care about Deriva or a Flow; our technologies are implementation details. Users will care about CFDE, and how to submit data to CFDE, so I'd suggest keeping `cfde-client` as the package and `cfde` as the command (or there can be bikeshedding around `cfde-client` vs. `cfde-submission-tool` vs. `cfde-data-submission`, etc., on which I have no opinion).

**Comment by NickolausDS** [comment]
That sounds sensible to me. If we expect there to be other CFDE clients, it might be prudent to name the client something more specific, like `cfde-submission-tool` or `cfde-data-submission`. But if not, I'm fine with `cfde-client`. 

We should change the repo name to match though. Especially if it's going to remain public.

**Comment by lliming** [comment]
There likely will be other CFDE clients in the future, so it is probably worth allowing for that now. I like cfde-submission-tool or something simpler like "cfde-submit".  I don't like including "data" in the name.

**Comment by NickolausDS** [comment]
Ok, how about `cfde-submit` then?

The process will look like this for users. 
```
$ pip install cfde-submit
$ cfde-submit login
$ cfde-submit run my_data_package.zip
$ cfde-submit status
$ cfde-submit logout
```

**Comment by lliming** [comment]
Let's see if @rpwagner agrees. I think the above looks good!

**Comment by rpwagner** [comment]
Looks good to me!

**Comment by NickolausDS** [comment]
Great! I'll go ahead and push to PyPi.

Any further objections if I also rename the [deriva-flow-client](https://github.com/nih-cfde/deriva-flow-client) to `cfde-submit` also?

**Comment by NickolausDS** [comment]
Done! The process looks like this:

```
pip install cfde-submit
cfde-submit login
cfde-submit run --service-instance dev mydataset.zip
cfde-submit status
```

You can install this now and play with it, but you will get a warning on login that "Submissions are Unavailable". This is due to the dev instance running but not prod. 

Lastly, since there were no objections, I'm renaming the repo to cfde-submit.
