### ISSUE TITLE
cfde-submit displays incorrect urls after action provider changes

### ISSUE THREAD

**Issue by DavidMichaelKelly** [nih-cfde/submission-workflow#40]
cfde-submit displays the wrong urls after recent action provider changes. For example, it will show the url as /CFDE/data/datapackage_* when the data is actually stored in /CFDE/public/<dcc>/datapackage_*

**Comment by NickolausDS** [comment]
I'm pretty sure this is my fault, I think there is a extra line outside of the `ingest()` function that generates that string

**Comment by NickolausDS** [comment]
Fixed in https://github.com/nih-cfde/cfde-submit/pull/17
