### ISSUE TITLE
cfde-submit tool won't install

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/submission-workflow#43]
I'm having some kind of conflict with PyYAML:

```
Installing collected packages: PyYAML, globus-automate-client, cfde-submit
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 3.13
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
OS: MacOS BigSur 11.2.1

full output here: https://gist.github.com/ACharbonneau/ed9a83f1848b5e8273ed4dd8f04e126d

**Comment by DavidMichaelKelly** [comment]
Hi Amanda,

It looks like you're running into some python module conflicts. Are you trying to install cfde-submit from within a virtual environment? If not, creating one may help. There is some documentation about how to do this at https://docs.python.org/3/tutorial/venv.html. If that doesn't help, let me know and we can take a closer look at what's happening.

**Comment by ACharbonneau** [comment]
running in a VM gets me past the conflict, but I get this warning/error:

```globus-automate-client 0.10.7 has requirement globus-sdk<2.0,>=1.9, but you'll have globus-sdk 2.0.1 which is incompatible.```

**Comment by ACharbonneau** [comment]
I'm not sure if this should be a new issue or if it's due to the client error above, but I can't get the tool to let me do anything:

I tried logging in, and it doesn't ask me for any input, just tells me submissions are disabled. And it doesn't seem to remember my previous session, so I don't think it's trying to use cached credentials.

```
(cfdesubmit) (base) amandas-mbp-2:~ amanda$ cfde-submit login
Submissions have temporarily been disabled, please check with your Administrator.
(cfdesubmit) (base) amandas-mbp-2:~ amanda$ cfde-submit status
Submissions have temporarily been disabled, please check with your Administrator.
Flow not started and flow-id or flow-instance-id not specified
(cfdesubmit) (base) amandas-mbp-2:~ amanda$ cfde-submit run ~/cfde_repos/specifications-and-documentation/draft-C2M2_example_submission_data/HMP__sample_C2M2_Level_0_bdbag.contents/file.tsv
Please enter the CFDE identifier for your Data Coordinating Center: HMP
Thank you. Would you like to save 'HMP' for future submissions? y/n: n
Submissions have temporarily been disabled, please check with your Administrator.
Submit datapackage file.tsv using HMP? (y/N)? > N
Aborted. No data submitted.
(cfdesubmit) (base) amandas-mbp-2:~ amanda$ cfde-submit logout
You are not logged in
(cfdesubmit) (base) amandas-mbp-2:~ amanda$
```

**Comment by DavidMichaelKelly** [comment]
The cfde-submit tool runs on production by default, which is not accepting submissions at the moment. If you want to run on the staging instance, try running "export CFDE_SUBMIT_SERVICE_INSTANCE=staging" before the cfde-submit command.

I'll try to reproduce the module warnings you're seeing.

**Comment by ACharbonneau** [comment]
that makes sense.

**Comment by DavidMichaelKelly** [comment]
The issue with requirement warnings during installation should be resolved now. It will be available in the next release
