### ISSUE TITLE
Cancelling login doesn't actually cancel log in

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/submission-workflow#45]
When you try to login, the screen says that to cancel the login process, you do 'control + C', but when I do that, it doesn't actually cancel my login, it just makes me do it manually. The behavior is confusing.

```
You have been logged out
(cfdesubmit) (base) amandas-mbp-2:~ amanda$ cfde-submit login
Running on service 'staging'
Starting login with Globus Auth, press ^C to cancel.
^CPlease paste the following URL in a browser:
https://auth.globus.org/v2/oauth2/authorize?client_id=417301b1-5101-456a-8a27-423e71a2ae26&redirect_uri=https%3A%2F%2Fauth.globus.org%2Fv2%2Fweb%2Fauth-code&scope=https%3A%2F%2Fauth.globus.org%2Fscopes%2Feec9b274-0c81-4334-bdc2-54e90e689b9a%2Fmanage_flows+https%3A%2F%2Fauth.globus.org%2Fscopes%2Feec9b274-0c81-4334-bdc2-54e90e689b9a%2Fview_flows+https%3A%2F%2Fauth.globus.org%2Fscopes%2Feec9b274-0c81-4334-bdc2-54e90e689b9a%2Frun+https%3A%2F%2Fauth.globus.org%2Fscopes%2Feec9b274-0c81-4334-bdc2-54e90e689b9a%2Frun_status+https%3A%2F%2Fauth.globus.org%2Fscopes%2F0e57d793-f1ac-4eeb-a30f-643b082d68ec%2Fhttps+https%3A%2F%2Fauth.globus.org%2Fscopes%2F922ee14d-49b7-4d69-8f1c-8e2ff8207542%2Fhttps+https%3A%2F%2Fauth.globus.org%2Fscopes%2F86453578-04b5-4c72-9188-8a6db9804135%2Fflow_86453578_04b5_4c72_9188_8a6db9804135_user&state=_default&response_type=code&code_challenge=eQEiBnvfoTnZta0xb-Mu6Le0xVKfkrCxndktFv111L0&code_challenge_method=S256&access_type=online&prefill_named_grant=CfdeClient+Login
Please Paste your Auth Code Below:
<code pasted here>
You are authenticated and your tokens have been cached.
```

**Comment by NickolausDS** [comment]
This is good user-experience feedback. The tool itself is built to be run in both a desktop environment and a within an SSH session, and includes a fallback mechanism in case it incorrectly detected an SSH env. The first ^C triggers the fallback, and a second will cancel authentication altogether. 

But in this case, it sounds like the fallback is just confusing? If that's the case, we could make the first ^C cancel authentication, and provide additional login flags in the unlikely event the user needs them. How does that sound?

**Comment by ACharbonneau** [comment]
Maybe leave the functionality as is (I had it fail auth and needed to do the manual way once, so it definitely has utility) but change the text to say something more like:

`Starting login with Globus Auth, press ^C twice to cancel or once to manually authenticate`

?

**Comment by NickolausDS** [comment]
Sure, that's an easy fix.

**Comment by DavidMichaelKelly** [comment]
This should be resolved with Nick's pull request and will be available in the next cfde-submit release
