### ISSUE TITLE
Not clear what "CFDE identifier" refers to

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/submission-workflow#46]
When I try to submit, it says `Please enter the CFDE identifier for your Data Coordinating Center:`

I'm not sure what identifier this is referring to. Is it just a free-text descriptor for the user? Or an actual identifier in Deriva that the user is expected to know?

**Comment by DavidMichaelKelly** [comment]
The CFDE identifiers have the format of cfde_registry_dcc:group. For example, cfde_registry_dcc:gtex or cfde_registry_dcc:kidsfirst. The users would have to know that information before they could run the tool.

**Comment by ACharbonneau** [comment]
Is @fridayek doing the documentation for this tool? The docs will need either a listing the possible identifiers or instructions on where DCCs can find out what their identifiers are. I can't find that particular identifier used anywhere in the portal, so likely we need a list from @karlcz

**Comment by karlcz** [comment]
Ah, this is what I have referred to as the "identifier for a DCC, issued by CFDE-CC".  It is visible in the detailed record for an enrolled DCC in the registry.
1. Use the Data Review link to get to the submission system
2. Use the Submission System -> Enrolled DCCs link to get to a list of DCCs
3. The ID, as David mentioned, shows as something like `cfde_registry_dcc:dcc_abbrev` in the listing
You can also click on the document-inspection magnifier to see one record and this id is then displayed in the `ID` field. For example, if you've navigated all the way to [KidsFirst in staging env](https://app-staging.nih-cfde.org/chaise/record/#registry/CFDE:dcc/RID=34A)

These values are set by a human when we onboard a DCC and add them to this table.

**Comment by lliming** [comment]
This is covered in the cfde-submit documentation. See https://github.com/nih-cfde/cfde-submit/blob/main/docs/index.md#find-your-dccs-identifier
