### ISSUE TITLE
Documentation creation

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/submission-workflow#48]
My proposal, at least for now, is that:

- the submission team makes a first pass documentation as a markdown document(s) in a folder in whichever github repo makes sense (I think cfde-submit) and tell Amanda where it will be
- Make your folder using these basic instructions: https://github.com/nih-cfde/published-documentation#make-your-desired-changes-in-the-correct-repo 
- Amanda will wire your documentation folder into the main documentation website https://docs.nih-cfde.org/ so that the website automatically pulls changes in your documentation and publishes them

**Comment by lliming** [comment]
First cut at better documentation for `cfde-submit`is here:

https://github.com/nih-cfde/cfde-submit/tree/main/docs

The only two markdown files are:

/docs/index.md
/docs/install/index.md

The latter is mostly empty, as @DavidKelly999 will be filling it out. The former is ready to be looked at, though. I didn't find any specific markdown rules or conventions to follow in the basic instructions @ACharbonneau provided, so I just wrote generic Github markdown. I won't be surprised if I need to make changes to work with the build system you're using. Let me know! I'm also happy to make improvements based on feedback, of course.

**Comment by ACharbonneau** [comment]
basic markdown should be fine. The only thing that gets a little weird is linking across resources from different repos.
