### ISSUE TITLE
Prefer HTTPS if GCP is turned off or not accessible

### ISSUE THREAD

**Issue by NickolausDS** [nih-cfde/submission-workflow#50]
For cfde-submit, GCP is currently preferred if it is installed on the user's machine, but it does not check to see if GCP is running or can access the file. This results in the dataset 'hanging' on Globus, as it silently waits for the user to turn on GCP for the file transfer to initiate.

There are probably a couple things we could do to fix this. If GCP does an `operation_ls` on the file before attempting to start the transfer, it would ensure both criteria above:

* GCP is currently running
* GCP can access the file

This problem has been solved in another tool here: 

https://github.com/globusonline/pilot1-tools/blob/e8d8f6610657dc3d64b308ac8d6d0a0f437c7c9f/pilot/commands/endpoint_utils.py#L9

The tool above tests GCP is running both before a transfer is started and after the user logs in.

**Comment by ACharbonneau** [comment]
Update helppage when fixed https://github.com/nih-cfde/published-documentation/discussions/143#discussioncomment-411454

**Comment by DavidMichaelKelly** [comment]
This is resolved now in the epic2 bug fix branch. cfde-submit now uses HTTP for everything, unless the user runs with `cfde-submit run --globus mydata`. In cases where a user does specify --globus, but there is some type of GCS issue, cfde-submit will stop before the job is submitted and instead provide an error message with details about what went wrong and how to fix it.

**Comment by lliming** [comment]
Is the epic2 bug fix branch for this repo deployed in dev or staging yet?

**Comment by DavidMichaelKelly** [comment]
Sure, I can install it on dev and staging if that's useful. The epic2 bug fix branch can also be installed locally using the command:

pip install -e git+https://github.com/nih-cfde/cfde-submit@epic2_bug_fixes#egg=cfde-submit

I will be creating a new pypi release candidate very soon when the last few issues are resolved.

**Comment by ACharbonneau** [comment]
I updated my install and this seemed to work
