### ISSUE TITLE
Yes/No options in submission tool vary

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/submission-workflow#51]
The interface does not seem to actually be case sensitive, but the options suggest it is:

```
Thank you. Would you like to save 'cfde_registry_dcc:hmp' for future submissions? y/n: n
Running on service 'staging'
Submit datapackage  using cfde_registry_dcc:hmp? (y/N)? > y
```

Could we make them all lowercase so it's a little nicer?

**Comment by DavidMichaelKelly** [comment]
A fix for this has been committed and will be available in the next release
