### ISSUE TITLE
Support for users who belong to multiple DCCs

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/submission-workflow#57]
The tool asks “Would you like to save ‘cfde_registry_dcc:gtex’ for future submissions? y/n:” and I chose yes on the last one because I wasn’t paying enough attention and I can’t figure out how to unset it

Now I get:

```
(cfdesubmit) (base) amandas-mbp-2:cfde-release amanda$ cfde-submit run gtex-motrpac/motrpac/
Using saved DCC 'cfde_registry_dcc:gtex'
Running on service 'staging'
Submit datapackage  using cfde_registry_dcc:gtex? (y/N)? > n
Aborted. No data submitted.
(cfdesubmit) (base) amandas-mbp-2:cfde-release amanda$

```

there should be a way to reset.  maybe as simple as a `--reset` that forgets everything and gives you a fresh start

**Comment by ACharbonneau** [comment]
@karlcz told me about `--dcc-id` which helps a little, but isn't documented.

**Comment by ACharbonneau** [comment]
We might also want to consider a sticky setting for "never remember dcc id" because this will most likely lead them to make mistakes later as they alternate between different projects in different weeks/months

**Comment by DavidMichaelKelly** [comment]
You can change the default dcc by specifying --dcc-id, but if you don't want to have any saved dcc at all, you can now use "cfde-submit reset" to remove it.
