### ISSUE TITLE
Modify Submission Data Globus Endpoint ACLs to grant read access to other DCC groups

### ISSUE THREAD

**Issue by NickolausDS** [nih-cfde/submission-workflow#58]
Copying this issue from slack so we can track it

Currently, only DCC Submitters have access to write submissions, and read submitted data. The ACLS should be as follows:

Read/Write access to submit data:
* DCC Admins and DCC Submitters

Read-only access to submitted data:
* DCC Admins, Submitters, Approvers, Reviewers

**Comment by DavidMichaelKelly** [comment]
Submitted a fix
