### ISSUE TITLE
How to update the tool? How to check my version?

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/submission-workflow#60]
I can't find anything in the [current docs](https://github.com/nih-cfde/cfde-submit/blob/main/docs/index.md) about how to update my local tool. Are you expecting people to delete and reinstall it everytime you update? Does it update with pip? How will users know that the tool requires an update?

I tried checking my version, which is listed as an option in the `--help` but it's clearly not a real option:

![image](https://user-images.githubusercontent.com/1719360/109014178-e59c0c00-7681-11eb-99c5-dc7de39a1da5.png)

and just breaks

I'm clearly not using the latest version of the tool re: https://github.com/nih-cfde/submission-workflow/issues/59 but I'm not sure how I'm supposed to know that.

**Comment by DavidMichaelKelly** [comment]
Installation is managed through pip. I'll be creating our release candidate this morning and will give you the pip command to update it. To check the current version, run the command "cfde-submit version". I'll add a --version flag too.

**Comment by ACharbonneau** [comment]
Now that you say "cfde-submit version" I see that's what I was supposed to be getting from the command list...but I've never seen a tool tell me version info without `-` or `--` so I didn't get it. 

How will users know they need to update?

**Comment by DavidMichaelKelly** [comment]
In the latest release of cfde-submit, 0.1.9, you can run "cfde-submit --version".

To update to the latest version: python3 -m pip install --upgrade cfde-submit

There's also a feature in cfde-submit where we can set a minimum version requirement. If they are running a version prior to our requirement, they will get a message from about updating.

**Comment by ACharbonneau** [comment]
Is @lliming doing the documentation still? I'm wondering if I need to make new issues for each of these changes so they make it into the docs, or if just tagging them with documentation is enough

**Comment by lliming** [comment]
David and Nick are updating docs as changes are made to the tool. @fridayek may be doing something with the documentation from the cfde-submit repo (do you know how that's being handled, @ACharbonneau ?), so it would be helpful to keep her in the loop if doc changes are made.

**Comment by ACharbonneau** [comment]
These specific things have been addressed in docs
