### ISSUE TITLE
Auth workflow is really fragile

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/submission-workflow#61]
I'm using an HPCC, so when I submit it has me paste a URL in the browser and paste back an auth key. That works fine, except that when I press "allow" on the authorization screen, it starts spinning in my tab, but doesn't indicate that it's trying a URL in the bottom nav bar. If I just sit and wait it takes 10-15 seconds to actually come back with an auth code, and works fine. 

But if I accidentally double click allow, or think it's hung and click it again, on my second click it *does* start indicating that it's trying a URL in the bottom bar, so it looks to the user like it just didn't work on the first button click? But that second click reliably makes it error out to a bad gateway. When I go back to my tool session with no token, it tells me I couldn't log in. That's fine. But then it immediately continues trying to submit my package and errors out a second time, but less nicely.

I made a 45 second video:

https://user-images.githubusercontent.com/1719360/109020568-10895e80-7688-11eb-9945-110b07e3e6dd.mov

The two big issues as a user are:

As a user, the auth thing seems to sit a long time. If I just wait for it, it's usually about 15 seconds, which is long enough that I get antsy and try the "allow" button again. 

When I go back to my browser and get `Unable to login: Failed to get an auth_code from Globus Auth.` the behavior I expect is that now my prompt is back to `$`. So, even though I've just done this 4 times in a row to make a video, my first instinct is still to re-enter my `cfde-submit run` call to try again, which just makes the whole thing vomit error messages. It's weird to give me a red failure error, and then keep going. 

Possible fixes:

- On other sites where clicking more than once ruins everything, the site tells me that. So a quick fix could be just having the 'allow' page say something like "This operation will take several seconds, only click once and do not reload this page"

- I really think that if the tool is going to throw a red error, it needs to also stop that workflow and put me back at `$`

- OR the flow should step back, give me a new URL and let me try to auth again.

**Comment by lliming** [comment]
Nick and David brought this up with the Globus team and they were aware of it already and are working on a fix. However, since this is in a service CFDE doesn't operate, (a) our team can track the issue, but none of us can fix it; (b) while we may get a fix before our release next week, we shouldn't count on it; and (c) the fix won't require CFDE to change anything in our systems, so Globus can fix it as soon as they're ready without us planning a release.

**Comment by ACharbonneau** [comment]
the paste a link get back an auth code is suddenly way, way faster today, so maybe this is fixed?

**Comment by DavidMichaelKelly** [comment]
I noticed this too. I've had to authenticate several times today and it has been very quick each time.

**Comment by lliming** [comment]
The Globus team has tried to replicate the slow response to the consent screen. While that's been happening, they've been changing things in the background that have likely affected the performance, so they believe it's less likely we'll see a multi0second delay anymore.

More importantly (I think?), they have set up an upcoming change (not released yet) that will disable the "Allow" button when it is clicked, preventing button-mashing and the resulting error. I will update this issue when that change has been released.

**Comment by lliming** [comment]
This issue has two pieces: the slow response time issue (which makes it tempting to mash the "Allow" button) and the fact that mashing the "Allow" button results in an error.  The slow response time issue appears to be much better now as a result of changes made by the Globus team on the back-end of the system. So it's now less likely that people will feel a need to press the "Allow" button more than once. 

In regard to the "Allow" button behavior, the Globus team has scheduled release of an improved "Allow" button that animates when pressed (indicating that it's "working") and disables subsequent presses. Pending the usual release testing process, this is scheduled for release on 3/17.  I'll watch for the release, try it out when it happens, and update this issue. I think when those things happen, we should be able to close this issue?

**Comment by lliming** [comment]
Globus has released the change to the Allow button behavior I mentioned above. It should no longer be possible to mash the Allow button. I think this resolves this issue and I'm moving this issue to the Review/QA pipeline.

**Comment by ACharbonneau** [comment]
this has been working fine for at least two weeks.
