### ISSUE TITLE
remove level 0 and level 1 references from docs

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/submission-workflow#64]
Currently the docs have a little summary about the model, but @abradyIGS is currently working to remove the level 0/level 1 nomenclature from the docs, so this needs to be updated too

**Comment by lliming** [comment]
What's the new nomenclature? When the C2M2 docs are updated, we can change here also. Unless you think we don't need to say anything about the difference between Level 0 and Level 1 in this doc?

**Comment by lliming** [comment]
Hi @ACharbonneau , we are trying to determine if this should be a blocker for the release or not. I think probably not because I don't think the docs are part of what's being released. Please correct me if I'm mistaken.

**Comment by ACharbonneau** [comment]
We can't give people the submission tool with no documentation on how to use it.

**Comment by ACharbonneau** [comment]
I just removed the references.
