### ISSUE TITLE
Docs - add info about dryrun mode & about BDbag input options

### ISSUE THREAD

**Issue by lliming** [nih-cfde/submission-workflow#66]
"the docs don’t explain several of the run options currently, or how to do submissions that aren’t just from a folder"

**Comment by ACharbonneau** [comment]
it doesn't look like this ever got added

**Comment by lliming** [comment]
@DavidKelly999 , could you please add this to your current list of to-dos and have something ready by the end of February? I don't think this needs to wait for a portal release, as the documentation pages are hosted separately.

**Comment by DavidMichaelKelly** [comment]
Info about dry run mode and a few other undocumented options have been added to the documentation in the fair-assessment branch of cfde-submit. This will be merged into the main branch when the final release is created
