### ISSUE TITLE
To Do note rendering on website

### ISSUE THREAD

**Issue by marisalim** [nih-cfde/submission-workflow#72]
There is a 'To Do' note on the Submission Tool [page](https://docs.nih-cfde.org/en/latest/cfde-submit/docs/#find-your-dccs-identifier). Is that supposed to be rendering on the website?
```
[TODO: The link above will not work until the production portal has been updated. When the production portal is updated, make sure it works!]
```

**Comment by DavidMichaelKelly** [comment]
That todo link was removed last week in the epic2 bug fix branch (https://github.com/nih-cfde/cfde-submit/commit/30b70fa9b62d6beed5b15ae336ac26b74f77d1f0). That branch is where I've been putting my recent documentation changes

**Comment by marisalim** [comment]
Hm I still see some to do messages, but just a note that they can be hidden with `<to do >` when rendered on the website <to do> instead of using the `[to do]` which still render.

**Comment by DavidMichaelKelly** [comment]
This should be resolved - verified there were no "to do" tags in docs/index.md or docs/install/index.md
