### ISSUE TITLE
Update docs: installing cfde-submit on clusters

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/submission-workflow#76]
David did a bunch of trouble shooting with ExRNA to get their cluster to install the cfde-submit tool, and I'd like to capture the useful stuff either in the docs for the tool, or in the [troubleshooting forum thing](https://github.com/nih-cfde/published-documentation/discussions), whichever makes more sense. But the resolution happened while I wasn't there, so I don't know what actually worked. 

@DavidKelly999 can you write this/help me write this?

**Comment by ACharbonneau** [comment]
I have an update from ExRNA:

> cfde-submit was installed on cluster, but it would crash when I tried cfde-submit login.

So I think he still needs some help.

**Comment by DavidMichaelKelly** [comment]
The issue is pretty specific to that particular cluster: the version of gcc installed on their cluster fails to compile the python cryptography package (a package required by cfde-submit). We were able to get further by using modules to load a different version of gcc. I'll reach out to get more info about the other error he was seeing.

**Comment by DavidMichaelKelly** [comment]
A few quick updates: I forgot to mention that we'd also installed cfde-submit on his laptop without any of the issues we saw on his cluster. This morning, David mentioned one of his colleagues may have found a solution to the login issue, but he would like to focus on some data issues before coming back to this.

**Comment by DavidMichaelKelly** [comment]
I believe this should be resolved. It was a strange issue with their development environment that prevented some packages from being built correctly. I don't think there's much general info we could extract and add to the docs.
