### ISSUE TITLE
cfde-submit fragile to zipfile renaming

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/submission-workflow#79]
If I obtain an existing submission zipfile and try to resubmit, it seems to break unless I rename the zipfile such that the basename of the zipfile matches the top-level directory name inside the archive.

1. Download a successful submission zipfile
2. Rename to anything other than the archive content (or keep original download name which is already a rename!)
3. Run `cfde-submit ... yourfile.zip`  on a suitable dev/staging VPC

The error looks something like

```
TableSchema invalid due to the following errors: 
Path '/tmp/bag_gpgvz7ze/yourfile' does not refer to a file
```

**Comment by DavidMichaelKelly** [comment]
Added Nick's fix to the bug fix branch
