### ISSUE TITLE
Sync/test Prod AP with code from Staging/Dev

### ISSUE THREAD

**Issue by jgaff** [nih-cfde/submission-workflow#8]
After https://github.com/nih-cfde/systems-infrastructure/issues/14 is complete, migrate the Staging code to Prod and verify the Prod AP is functional.

**Comment by jgaff** [comment]
Transitioning to @NickolausDS, who is handling the AP development and deployment going forward.

**Comment by DavidMichaelKelly** [comment]
I believe this is an older issue that can be closed. The prod ap is running the latest stable releases.
