### ISSUE TITLE
Change display name in client registration

### ISSUE THREAD

**Issue by lliming** [nih-cfde/submission-workflow#82]
The client registration we’re using for the `cfde-submit` tool currently has the display name “CFDE Native App”. This should be changed to “cfde-submit command-line utility” or something similar (maybe just “cfde-submit utility”?) so it’s clearer what it is when this appears in consent screens and other Auth pages.

**Comment by DavidMichaelKelly** [comment]
The display name has been updated to "cfde-submit utility"
