### ISSUE TITLE
Mechanism to copy new data packages to FAIR assessment VM (dev)

### ISSUE THREAD

**Issue by lliming** [nih-cfde/submission-workflow#85]
- Setup a GCS endpoint on the FAIR assessment VM in dev, create a guest collection, assign permission to a client credential that permits data packages to be copied to the collection for use by the FAIR assessment code
- Use a test flow to confirm the Transfer action provider can be used to transfer in a copy of a data package (this is mostly about making sure permissions are set in a way that allows these transfers using a client credential available in the flow)
- if necessary, add the client credential to a group that already has permission to read all of the data packages on the existing GCS endpoint

**Comment by DavidMichaelKelly** [comment]
This is finished, but was done in a slightly different way. Instead of creating a new GCS endpoint, cfde-submit makes the existing GCS HTTPS access token available to the workflow. The workflow passes the token to the funcx function, which then downloads the data itself via the requests library
