### ISSUE TITLE
Ingest FAIR assessment results into Deriva submission catalog (dev)

### ISSUE THREAD

**Issue by lliming** [nih-cfde/submission-workflow#87]
- When @karlcz is able to provide Deriva client code, deploy it on the FAIR assessment VM for dev and confirm that it ingests an assessment result produced by @u8sand 's assessment code.
- Using a test flow, confirm the Deriva client code can be used in a FuncX function (necessary credentials are accessible)

**Comment by lliming** [comment]
Karl C. says:
Unfortunately, it seems NaN is not supported by the standard JSON serialization rules for numbers, Postgresql adheres tightly to those specs, and we rely on the DB to do json (de)serialization.  Python seems to be a little looser and will serialize a non-comformant document:
```
>>> json.dumps({"value": math.nan})
'{"value": NaN}'
```
but Postgresql will not deserialize it:
```
=> select '{"foo": NaN}'::jsonb;
ERROR:  invalid input syntax for type json
LINE 1: select '{"foo": NaN}'::jsonb;
               ^
DETAIL:  Token "NaN" is invalid.
CONTEXT:  JSON data, line 1: {"foo": NaN...
```
We might be able to abuse some implicit type-casting behaviors and pass a string:
```
select '{"foo": "NaN"}'::jsonb;
     jsonb      
----------------
 {"foo": "NaN"}

```
but this seems a little flaky to me... So, I think we probably should not try to store and retrieve the NaN to indicate a failed measurement.  We should decide whether to skip registration of such failed measurements or to allow the value field to also be nullable and replace with null.

**Comment by lliming** [comment]
@DavidKelly999 is working on this and is getting close to first runs against Deriva. Latest I heard was he's waiting on permissions to be set in Deriva to allow loading results into the right tables, and he expected Karl to have that for him soon.

**Comment by DavidMichaelKelly** [comment]
This has been completed
