### ISSUE TITLE
Add FAIR assessments to submission flow (staging)

### ISSUE THREAD

**Issue by lliming** [nih-cfde/submission-workflow#89]
This will enable testing FAIR assessments for submissions in the staging environment.

When #88 and subsequent testing are done, create a new version of submission flow for the staging environment that includes:

    transferring the data package to the FAIR assessment VM (Transfer AP)
    running the FAIR assessment code and generating an assessment (FuncX AP)
    ingesting the assessment into Deriva's submission catalog for the corresponding submission (FuncX AP)

Deploy the new flow and change the cfde-submit configuration to use the new flow for the staging environment.

**Comment by DavidMichaelKelly** [comment]
The assessment runs on submissions to staging
