### ISSUE TITLE
(Hold) Modify AP to use registry catalog appropriately

### ISSUE THREAD

**Issue by jgaff** [nih-cfde/submission-workflow#9]
Registry catalog interaction not yet specified

**Comment by jgaff** [comment]
Transitioning to @NickolausDS, who is handling the AP development moving forward.

**Comment by NickolausDS** [comment]
I believe this should be taken care of in the epic2 upgrade #18. Interactions the AP has with Deriva have been substantially reduced and limited to the new epic2 Submission client.
