### ISSUE TITLE
Add FAIR assessments to submission flow (production)

### ISSUE THREAD

**Issue by lliming** [nih-cfde/submission-workflow#90]
This will enable testing FAIR assessments for submissions in the production environment.

When #89 and subsequent testing are done, create a new version of submission flow for the production environment that includes:

- transferring the data package to the FAIR assessment VM (Transfer AP)
- running the FAIR assessment code and generating an assessment (FuncX AP)
- ingesting the assessment into Deriva's submission catalog for the corresponding submission (FuncX AP)

Deploy the new flow and change the cfde-submit configuration to use the new flow for the production environment.

**Comment by DavidMichaelKelly** [comment]
This is completed and now using parallel cluster in dev, staging, and prod
