### ISSUE TITLE
Permissions audit tool for Globus collections

### ISSUE THREAD

**Issue by lliming** [nih-cfde/submission-workflow#93]
We need a tool that can be run by authorized CFDE CC personnel (e.g., @rpwagner , @DavidKelly999 , @lliming ) that:

1. Retrieves and prints out the ACLs on the Globus guest collection used by the submission flow. 
2. Retrieves and prints out the DCC submission permissions configured in Deriva.

It's fair to assume the individual running the tool will have access manager permissions on the guest collection and thus can see the ACLs.  It's also fair to assume the individual will have the necessary permissions in Deriva to retrieve the configured permissions.  Finally, the tool does not need to compare the two sets of permissions: the individual using the tool will do it visually/manually.

**Comment by DavidMichaelKelly** [comment]
The audit tool has been created and is available now in the submission-workflow repo
